export const AppConstants = {
  STORAGE_KEY_PRESETS: '@STORAGE_KEY_PRESETS',
  STORAGE_KEY_AUTOCHANGE_ICON: '@STORAGE_KEY_PRESETS',
  BORDER_RADIUS: 4,
  TYPE_BRIGHTNESS: 'brightness',
  TYPE_VOLUME: 'volume',
  TYPE_SILENT: 'silent',
};
